// Central definition of all queryable fields and filters per collection.
// path   = MongoDB document path (dot notation)
// label  = Human-readable name shown in UI
// type   = string | number | date | boolean

const fieldMaps = {
  employees: {
    collectionName: 'employees',
    label: 'Employees',
    fields: {
      employeeId:       { path: 'employeeId',                                        label: 'Employee ID',        type: 'string' },
      status:           { path: 'status',                                            label: 'Status',             type: 'string' },
      firstName:        { path: 'personalInfo.firstName',                            label: 'First Name',         type: 'string' },
      lastName:         { path: 'personalInfo.lastName',                             label: 'Last Name',          type: 'string' },
      preferredName:    { path: 'personalInfo.preferredName',                        label: 'Preferred Name',     type: 'string' },
      dateOfBirth:      { path: 'personalInfo.dateOfBirth',                          label: 'Date of Birth',      type: 'date'   },
      personalEmail:    { path: 'personalInfo.personalEmail',                        label: 'Personal Email',     type: 'string' },
      phoneNumber:      { path: 'personalInfo.phoneNumber',                          label: 'Phone Number',       type: 'string' },
      homeCity:         { path: 'personalInfo.address.city',                         label: 'Home City',          type: 'string' },
      homeCountry:      { path: 'personalInfo.address.country',                      label: 'Home Country',       type: 'string' },
      workEmail:        { path: 'workInfo.workEmail',                                label: 'Work Email',         type: 'string' },
      jobTitle:         { path: 'workInfo.title',                                    label: 'Job Title',          type: 'string' },
      department:       { path: 'workInfo.department',                               label: 'Department',         type: 'string' },
      subDepartment:    { path: 'workInfo.subDepartment',                            label: 'Sub Department',     type: 'string' },
      costCenter:       { path: 'workInfo.costCenter',                               label: 'Cost Center',        type: 'string' },
      businessUnit:     { path: 'workInfo.businessUnit',                             label: 'Business Unit',      type: 'string' },
      employmentType:   { path: 'workInfo.employmentType',                           label: 'Employment Type',    type: 'string' },
      employmentStatus: { path: 'workInfo.employmentStatus',                         label: 'Employment Status',  type: 'string' },
      startDate:        { path: 'workInfo.startDate',                                label: 'Start Date',         type: 'date'   },
      endDate:          { path: 'workInfo.endDate',                                  label: 'End Date',           type: 'date'   },
      managerName:      { path: 'workInfo.manager.name',                             label: 'Manager Name',       type: 'string' },
      managerEmail:     { path: 'workInfo.manager.email',                            label: 'Manager Email',      type: 'string' },
      managerTitle:     { path: 'workInfo.manager.title',                            label: 'Manager Title',      type: 'string' },
      siteCode:         { path: 'workInfo.location.siteCode',                        label: 'Site Code',          type: 'string' },
      officeCity:       { path: 'workInfo.location.city',                            label: 'Office City',        type: 'string' },
      officeCountry:    { path: 'workInfo.location.country',                         label: 'Office Country',     type: 'string' },
      remoteStatus:     { path: 'workInfo.location.remoteStatus',                    label: 'Remote Status',      type: 'string' },
      floor:            { path: 'workInfo.location.building.floor',                  label: 'Floor',              type: 'number' },
      deskNumber:       { path: 'workInfo.location.building.deskNumber',             label: 'Desk Number',        type: 'string' },
      zone:             { path: 'workInfo.location.building.floorPlan.zone',         label: 'Zone',               type: 'string' },
      currency:         { path: 'compensation.currency',                             label: 'Currency',           type: 'string' },
      annualBaseSalary: { path: 'compensation.structure.annualBaseSalary',           label: 'Annual Base Salary', type: 'number' },
      salaryBand:       { path: 'compensation.structure.components.details.salaryBand', label: 'Salary Band',    type: 'string' },
      createdAt:        { path: 'metadata.createdAt',                                label: 'Created At',         type: 'date'   },
      updatedAt:        { path: 'metadata.updatedAt',                                label: 'Updated At',         type: 'date'   },
    },
    filters: {
      status:           { path: 'status',                          label: 'Status',           type: 'select', options: ['Active', 'Inactive'] },
      department:       { path: 'workInfo.department',             label: 'Department',       type: 'select', options: ['Information Technology', 'Human Resources', 'Finance', 'Engineering', 'Sales', 'Marketing', 'Legal & Compliance', 'Operations'] },
      employmentStatus: { path: 'workInfo.employmentStatus',       label: 'Emp. Status',      type: 'select', options: ['Active', 'Terminated'] },
      employmentType:   { path: 'workInfo.employmentType',         label: 'Emp. Type',        type: 'select', options: ['Full-Time', 'Part-Time', 'Contract'] },
      siteCode:         { path: 'workInfo.location.siteCode',      label: 'Site',             type: 'select', options: ['NYC-HQ', 'LON-EU', 'BLR-IND', 'SYD-APC'] },
      remoteStatus:     { path: 'workInfo.location.remoteStatus',  label: 'Remote Status',    type: 'select', options: ['On-Site', 'Hybrid', 'Remote'] },
      startDateFrom:    { path: 'workInfo.startDate',              label: 'Start Date From',  type: 'date',   operator: 'gte' },
      startDateTo:      { path: 'workInfo.startDate',              label: 'Start Date To',    type: 'date',   operator: 'lte' },
    },
  },

  onboarding: {
    collectionName: 'onboarding',
    label: 'Onboarding',
    fields: {
      onboardingId:       { path: 'onboardingId',                              label: 'Onboarding ID',      type: 'string' },
      employeeId:         { path: 'employeeId',                                label: 'Employee ID',        type: 'string' },
      employeeName:       { path: 'employeeName',                              label: 'Employee Name',      type: 'string' },
      department:         { path: 'department',                                label: 'Department',         type: 'string' },
      status:             { path: 'status',                                    label: 'Status',             type: 'string' },
      onboardingBatch:    { path: 'onboardingBatch',                           label: 'Batch',              type: 'string' },
      startedDate:        { path: 'startedDate',                               label: 'Started Date',       type: 'date'   },
      completedDate:      { path: 'completedDate',                             label: 'Completed Date',     type: 'date'   },
      hrContactName:      { path: 'hrContact.name',                            label: 'HR Contact',         type: 'string' },
      hrContactEmail:     { path: 'hrContact.email',                           label: 'HR Contact Email',   type: 'string' },
      buddyName:          { path: 'assignedBuddy.name',                        label: 'Buddy Name',         type: 'string' },
      trainingPlatform:   { path: 'training.platform',                         label: 'Training Platform',  type: 'string' },
      accessCompletedDate:{ path: 'accessProvisioning.completedDate',          label: 'Access Granted On',  type: 'date'   },
      createdAt:          { path: 'metadata.createdAt',                        label: 'Created At',         type: 'date'   },
    },
    filters: {
      status:          { path: 'status',           label: 'Status',       type: 'select', options: ['Completed', 'In Progress', 'Not Started'] },
      department:      { path: 'department',        label: 'Department',   type: 'select', options: ['Information Technology', 'Human Resources', 'Finance', 'Engineering', 'Sales', 'Marketing', 'Legal & Compliance', 'Operations'] },
      onboardingBatch: { path: 'onboardingBatch',  label: 'Batch',        type: 'text' },
      startedFrom:     { path: 'startedDate',      label: 'Started From', type: 'date', operator: 'gte' },
      startedTo:       { path: 'startedDate',      label: 'Started To',   type: 'date', operator: 'lte' },
    },
  },

  offboarding: {
    collectionName: 'offboarding',
    label: 'Offboarding',
    fields: {
      offboardingId:        { path: 'offboardingId',                   label: 'Offboarding ID',      type: 'string' },
      employeeId:           { path: 'employeeId',                      label: 'Employee ID',          type: 'string' },
      employeeName:         { path: 'employeeName',                    label: 'Employee Name',        type: 'string' },
      department:           { path: 'department',                      label: 'Department',           type: 'string' },
      separationType:       { path: 'separationType',                  label: 'Separation Type',      type: 'string' },
      status:               { path: 'status',                          label: 'Status',               type: 'string' },
      initiatedDate:        { path: 'initiatedDate',                   label: 'Initiated Date',       type: 'date'   },
      lastWorkingDay:       { path: 'lastWorkingDay',                  label: 'Last Working Day',     type: 'date'   },
      completedDate:        { path: 'completedDate',                   label: 'Completed Date',       type: 'date'   },
      exitInterviewDone:    { path: 'exitInterviewCompleted',          label: 'Exit Interview Done',  type: 'boolean'},
      exitInterviewDate:    { path: 'exitInterviewDate',               label: 'Exit Interview Date',  type: 'date'   },
      hrContactName:        { path: 'hrContact.name',                  label: 'HR Contact',           type: 'string' },
      severanceEligible:    { path: 'finalPayroll.severanceEligible',  label: 'Severance Eligible',   type: 'boolean'},
      severanceWeeks:       { path: 'finalPayroll.severanceWeeks',     label: 'Severance Weeks',      type: 'number' },
      finalPayDate:         { path: 'finalPayroll.finalPayDate',       label: 'Final Pay Date',       type: 'date'   },
      ktCompleted:          { path: 'knowledgeTransfer.documentationCompleted', label: 'KT Completed', type: 'boolean'},
      handoverToName:       { path: 'knowledgeTransfer.handoverTo.name', label: 'Handover To',        type: 'string' },
    },
    filters: {
      separationType: { path: 'separationType', label: 'Separation Type', type: 'select', options: ['Voluntary Resignation', 'Involuntary Termination', 'Retirement', 'Contract End', 'Mutual Separation', 'Redundancy'] },
      department:     { path: 'department',      label: 'Department',      type: 'select', options: ['Information Technology', 'Human Resources', 'Finance', 'Engineering', 'Sales', 'Marketing', 'Legal & Compliance', 'Operations'] },
      status:         { path: 'status',          label: 'Status',          type: 'select', options: ['Completed', 'In Progress'] },
      lwdFrom:        { path: 'lastWorkingDay',  label: 'LWD From',        type: 'date', operator: 'gte' },
      lwdTo:          { path: 'lastWorkingDay',  label: 'LWD To',          type: 'date', operator: 'lte' },
    },
  },

  services: {
    collectionName: 'services',
    label: 'Services',
    fields: {
      serviceId:          { path: 'serviceId',                                  label: 'Service ID',         type: 'string' },
      employeeId:         { path: 'employeeId',                                 label: 'Employee ID',        type: 'string' },
      employeeName:       { path: 'employeeName',                               label: 'Employee Name',      type: 'string' },
      department:         { path: 'department',                                 label: 'Department',         type: 'string' },
      status:             { path: 'status',                                     label: 'Status',             type: 'string' },
      assignedDate:       { path: 'assignedDate',                               label: 'Assigned Date',      type: 'date'   },
      removedDate:        { path: 'removedDate',                                label: 'Removed Date',       type: 'date'   },
      deploymentMethod:   { path: 'deploymentMethod',                           label: 'Deployment Method',  type: 'string' },
      appName:            { path: 'application.name',                           label: 'App Name',           type: 'string' },
      appVendor:          { path: 'application.vendor',                         label: 'Vendor',             type: 'string' },
      appCategory:        { path: 'application.category',                       label: 'Category',           type: 'string' },
      appVersion:         { path: 'application.version',                        label: 'Version',            type: 'string' },
      supportTier:        { path: 'application.provider.supportTier',           label: 'Support Tier',       type: 'string' },
      accountManager:     { path: 'application.provider.accountManager',        label: 'Account Manager',    type: 'string' },
      licenseId:          { path: 'subscription.licenseId',                     label: 'License ID',         type: 'string' },
      assignedSeat:       { path: 'subscription.assignedSeat',                  label: 'Assigned Seat',      type: 'string' },
      seatType:           { path: 'subscription.seatType',                      label: 'Seat Type',          type: 'string' },
      costPerSeatUsd:     { path: 'subscription.costPerSeatUsd',                label: 'Cost/Seat (USD)',     type: 'number' },
      billingCycle:       { path: 'subscription.billingCycle',                  label: 'Billing Cycle',      type: 'string' },
      expiryDate:         { path: 'subscription.expiryDate',                    label: 'Expiry Date',        type: 'date'   },
      lastActiveDate:     { path: 'usage.lastActiveDate',                        label: 'Last Active',        type: 'date'   },
      totalLogins:        { path: 'usage.totalLogins',                           label: 'Total Logins',       type: 'number' },
      auditStatus:        { path: 'compliance.auditStatus',                      label: 'Audit Status',       type: 'string' },
      dataClassification: { path: 'compliance.dataClassification',               label: 'Data Classification',type: 'string' },
    },
    filters: {
      status:         { path: 'status',                    label: 'Status',        type: 'select', options: ['Active', 'Inactive'] },
      department:     { path: 'department',                label: 'Department',    type: 'select', options: ['Information Technology', 'Human Resources', 'Finance', 'Engineering', 'Sales', 'Marketing', 'Legal & Compliance', 'Operations'] },
      appCategory:    { path: 'application.category',     label: 'App Category',  type: 'select', options: ['Productivity Suite', 'Collaboration', 'Version Control', 'Project Management', 'ITSM', 'HR System', 'Analytics', 'Endpoint Security', 'Network Security', 'Identity & Access', 'Password Management', 'Document Management', 'E-Signature'] },
      appVendor:      { path: 'application.vendor',       label: 'Vendor',        type: 'text' },
      billingCycle:   { path: 'subscription.billingCycle',label: 'Billing Cycle', type: 'select', options: ['Monthly', 'Annual'] },
      auditStatus:    { path: 'compliance.auditStatus',   label: 'Audit Status',  type: 'select', options: ['Compliant', 'Warning', 'Non-Compliant'] },
      assignedFrom:   { path: 'assignedDate',             label: 'Assigned From', type: 'date', operator: 'gte' },
      assignedTo:     { path: 'assignedDate',             label: 'Assigned To',   type: 'date', operator: 'lte' },
    },
  },

  events: {
    collectionName: 'events',
    label: 'Events',
    fields: {
      eventId:         { path: 'eventId',                              label: 'Event ID',         type: 'string' },
      employeeId:      { path: 'employeeId',                           label: 'Employee ID',      type: 'string' },
      employeeName:    { path: 'employeeName',                         label: 'Employee Name',    type: 'string' },
      department:      { path: 'department',                           label: 'Department',       type: 'string' },
      eventType:       { path: 'eventType',                            label: 'Event Type',       type: 'string' },
      occurredAt:      { path: 'occurredAt',                           label: 'Occurred At',      type: 'date'   },
      title:           { path: 'eventInfo.title',                      label: 'Title',            type: 'string' },
      severity:        { path: 'eventInfo.severity',                   label: 'Severity',         type: 'string' },
      module:          { path: 'eventInfo.module',                     label: 'Module',           type: 'string' },
      environment:     { path: 'eventInfo.context.environment',        label: 'Environment',      type: 'string' },
      region:          { path: 'eventInfo.context.region',             label: 'Region',           type: 'string' },
      triggerType:     { path: 'eventInfo.context.trigger.triggerType',label: 'Trigger Type',     type: 'string' },
      initiatedBy:     { path: 'eventInfo.context.trigger.initiatedBy',label: 'Initiated By',    type: 'string' },
      relatedEntityType:{ path: 'payload.relatedEntityType',           label: 'Related Entity',   type: 'string' },
      relatedEntityId: { path: 'payload.relatedEntityId',              label: 'Related Entity ID',type: 'string' },
      performedBy:     { path: 'audit.performedBy',                    label: 'Performed By',     type: 'string' },
      performedByType: { path: 'audit.performedByType',                label: 'Performed By Type',type: 'string' },
      approvalStatus:  { path: 'audit.approval.status',                label: 'Approval Status',  type: 'string' },
      sourceSystem:    { path: 'audit.sourceSystem',                   label: 'Source System',    type: 'string' },
    },
    filters: {
      eventType: { path: 'eventType',         label: 'Event Type',   type: 'select', options: ['EMPLOYEE_HIRED', 'ONBOARDING_STARTED', 'ONBOARDING_COMPLETED', 'DEVICE_ASSIGNED', 'DEVICE_RETURNED', 'SERVICE_PROVISIONED', 'SERVICE_DEPROVISIONED', 'ACCESS_GRANTED', 'ACCESS_REVOKED', 'LICENSE_RENEWED', 'LICENSE_EXPIRED', 'COMPLIANCE_VIOLATION', 'PASSWORD_RESET', 'MFA_ENROLLED', 'OFFBOARDING_INITIATED', 'OFFBOARDING_COMPLETED', 'ROLE_CHANGED', 'DEPARTMENT_TRANSFER', 'TRAINING_COMPLETED', 'POLICY_ACKNOWLEDGED'] },
      severity:  { path: 'eventInfo.severity',label: 'Severity',     type: 'select', options: ['INFO', 'WARNING', 'CRITICAL'] },
      module:    { path: 'eventInfo.module',  label: 'Module',       type: 'select', options: ['HR', 'IT', 'Security', 'Finance', 'Compliance'] },
      department:{ path: 'department',        label: 'Department',   type: 'select', options: ['Information Technology', 'Human Resources', 'Finance', 'Engineering', 'Sales', 'Marketing', 'Legal & Compliance', 'Operations'] },
      occurredFrom:{ path: 'occurredAt',      label: 'From Date',    type: 'date', operator: 'gte' },
      occurredTo:  { path: 'occurredAt',      label: 'To Date',      type: 'date', operator: 'lte' },
    },
  },
};

module.exports = fieldMaps;
