// V2 approach: MongoDB does all the flattening — no arrays to unwind in employees
module.exports = [
  {
    $project: {
      _id: 0,
      employeeId:          1,
      status:              1,
      firstName:           '$personalInfo.firstName',
      lastName:            '$personalInfo.lastName',
      preferredName:       '$personalInfo.preferredName',
      dateOfBirth:         '$personalInfo.dateOfBirth',
      personalEmail:       '$personalInfo.personalEmail',
      phoneNumber:         '$personalInfo.phoneNumber',
      homeCity:            '$personalInfo.address.city',
      homeCountry:         '$personalInfo.address.country',
      homePostalCode:      '$personalInfo.address.postalCode',
      coordLat:            '$personalInfo.address.coordinates.lat',
      coordLng:            '$personalInfo.address.coordinates.lng',
      coordAccuracy:       '$personalInfo.address.coordinates.precision.accuracy',
      coordSource:         '$personalInfo.address.coordinates.precision.source',
      coordVerifiedBy:     '$personalInfo.address.coordinates.precision.verifiedBy',
      workEmail:           '$workInfo.workEmail',
      jobTitle:            '$workInfo.title',
      department:          '$workInfo.department',
      subDepartment:       '$workInfo.subDepartment',
      costCenter:          '$workInfo.costCenter',
      businessUnit:        '$workInfo.businessUnit',
      employmentType:      '$workInfo.employmentType',
      employmentStatus:    '$workInfo.employmentStatus',
      startDate:           '$workInfo.startDate',
      endDate:             '$workInfo.endDate',
      managerName:         '$workInfo.manager.name',
      managerEmail:        '$workInfo.manager.email',
      managerTitle:        '$workInfo.manager.title',
      managerPhone:        '$workInfo.manager.contact.phone',
      managerChannel:      '$workInfo.manager.contact.preferredChannel.type',
      siteCode:            '$workInfo.location.siteCode',
      officeCity:          '$workInfo.location.city',
      officeCountry:       '$workInfo.location.country',
      remoteStatus:        '$workInfo.location.remoteStatus',
      floor:               '$workInfo.location.building.floor',
      wing:                '$workInfo.location.building.wing',
      deskNumber:          '$workInfo.location.building.deskNumber',
      zone:                '$workInfo.location.building.floorPlan.zone',
      nearestMeetingRoom:  '$workInfo.location.building.floorPlan.nearestMeetingRoom',
      parkingBay:          '$workInfo.location.building.floorPlan.parkingBay',
      currency:            '$compensation.currency',
      annualBaseSalary:    '$compensation.structure.annualBaseSalary',
      annualBonusTarget:   '$compensation.structure.annualBonusTarget',
      salaryBand:          '$compensation.structure.components.details.salaryBand',
      salaryApprovedBy:    '$compensation.structure.components.details.approvedBy',
      lastReviewDate:      '$compensation.structure.components.details.lastReviewDate',
      createdAt:           '$metadata.createdAt',
      updatedAt:           '$metadata.updatedAt',
      dataSource:          '$metadata.dataSource',
    },
  },
];
