// V2 approach: MongoDB $unwind payload.changes[] → validation.rules[], then $project flat
module.exports = [
  { $unwind: { path: '$payload.changes', preserveNullAndEmptyArrays: true } },
  { $unwind: { path: '$payload.changes.validation.rules', preserveNullAndEmptyArrays: true } },
  {
    $project: {
      _id: 0,
      eventId:           1,
      employeeId:        1,
      employeeName:      1,
      department:        1,
      eventType:         1,
      occurredAt:        1,
      title:             '$eventInfo.title',
      severity:          '$eventInfo.severity',
      module:            '$eventInfo.module',
      environment:       '$eventInfo.context.environment',
      region:            '$eventInfo.context.region',
      ipAddress:         '$eventInfo.context.ipAddress',
      triggerType:       '$eventInfo.context.trigger.triggerType',
      initiatedBy:       '$eventInfo.context.trigger.initiatedBy',
      correlationId:     '$eventInfo.context.trigger.metadata.correlationId',
      traceId:           '$eventInfo.context.trigger.metadata.traceId',
      relatedEntityType: '$payload.relatedEntityType',
      relatedEntityId:   '$payload.relatedEntityId',
      changeField:       '$payload.changes.field',
      changeOldValue:    '$payload.changes.oldValue',
      changeNewValue:    '$payload.changes.newValue',
      changedAt:         '$payload.changes.changedAt',
      ruleSetId:         '$payload.changes.validation.ruleSetId',
      validationPassed:  '$payload.changes.validation.passed',
      ruleId:            '$payload.changes.validation.rules.ruleId',
      ruleName:          '$payload.changes.validation.rules.ruleName',
      rulePassed:        '$payload.changes.validation.rules.passed',
      ruleMessage:       '$payload.changes.validation.rules.message',
      performedBy:       '$audit.performedBy',
      performedByType:   '$audit.performedByType',
      sourceSystem:      '$audit.sourceSystem',
      approvalRequired:  '$audit.approval.required',
      approvalStatus:    '$audit.approval.status',
      reviewerName:      '$audit.approval.reviewer.name',
      reviewerRole:      '$audit.approval.reviewer.role',
      authMethod:        '$audit.approval.reviewer.credentials.authMethod',
      mfaVerified:       '$audit.approval.reviewer.credentials.mfaVerified',
      privilegedAccess:  '$audit.approval.reviewer.credentials.privilegedAccess',
    },
  },
];
