// V2 approach: MongoDB $unwind phases[] → tasks[] → verifications[], then $project flat
module.exports = [
  { $unwind: '$phases' },
  { $unwind: '$phases.tasks' },
  { $unwind: { path: '$phases.tasks.verifications', preserveNullAndEmptyArrays: true } },
  {
    $project: {
      _id: 0,
      offboardingId:        1,
      employeeId:           1,
      employeeName:         1,
      department:           1,
      separationType:       1,
      status:               1,
      initiatedDate:        1,
      lastWorkingDay:       1,
      completedDate:        1,
      exitInterviewDone:    '$exitInterviewCompleted',
      exitInterviewDate:    1,
      hrContactName:        '$hrContact.name',
      finalPayDate:         '$finalPayroll.finalPayDate',
      severanceEligible:    '$finalPayroll.severanceEligible',
      severanceWeeks:       '$finalPayroll.severanceWeeks',
      ktCompleted:          '$knowledgeTransfer.documentationCompleted',
      ktCompletedDate:      '$knowledgeTransfer.completedDate',
      handoverToName:       '$knowledgeTransfer.handoverTo.name',
      assetReturnStatus:    '$assetReturn.status',
      deviceSerialNumber:   { $arrayElemAt: ['$assetReturn.devices.serialNumber', 0] },
      deviceConditionGrade: { $arrayElemAt: ['$assetReturn.devices.condition.grade', 0] },
      deviceDisposition:    { $arrayElemAt: ['$assetReturn.devices.condition.assessment.disposition', 0] },
      deviceAssessedBy:     { $arrayElemAt: ['$assetReturn.devices.condition.assessment.assessedBy', 0] },
      phaseName:            '$phases.phaseName',
      phaseStatus:          '$phases.status',
      taskId:               '$phases.tasks.taskId',
      taskCategory:         '$phases.tasks.category',
      taskName:             '$phases.tasks.taskName',
      taskAssignedTo:       '$phases.tasks.assignedTo',
      taskStatus:           '$phases.tasks.status',
      taskDueDate:          '$phases.tasks.dueDate',
      taskCompletedDate:    '$phases.tasks.completedDate',
      verificationId:       '$phases.tasks.verifications.verificationId',
      verifiedBy:           '$phases.tasks.verifications.verifiedBy',
      verifiedAt:           '$phases.tasks.verifications.verifiedAt',
      verificationMethod:   '$phases.tasks.verifications.method',
      evidenceType:         '$phases.tasks.verifications.evidence.type',
      evidenceRefId:        '$phases.tasks.verifications.evidence.referenceId',
      evidenceStoredAt:     '$phases.tasks.verifications.evidence.storedAt',
      evidenceRetainYrs:    '$phases.tasks.verifications.evidence.retentionYears',
    },
  },
];
