// V2 approach: MongoDB $unwind phases[] → tasks[] → subtasks[], then $project flat
module.exports = [
  { $unwind: '$phases' },
  { $unwind: '$phases.tasks' },
  { $unwind: { path: '$phases.tasks.subtasks', preserveNullAndEmptyArrays: true } },
  {
    $project: {
      _id: 0,
      onboardingId:        1,
      employeeId:          1,
      employeeName:        1,
      department:          1,
      status:              1,
      onboardingBatch:     1,
      startedDate:         1,
      completedDate:       1,
      hrContactName:       '$hrContact.name',
      hrContactEmail:      '$hrContact.email',
      buddyName:           '$assignedBuddy.name',
      buddyEmail:          '$assignedBuddy.email',
      trainingPlatform:    '$training.platform',
      securityScore:       { $arrayElemAt: ['$training.modules.assessment.score', 0] },
      conductScore:        { $arrayElemAt: ['$training.modules.assessment.score', 1] },
      accessCompletedDate: '$accessProvisioning.completedDate',
      phaseName:           '$phases.phaseName',
      phaseStatus:         '$phases.status',
      phaseStartDate:      '$phases.startDate',
      phaseEndDate:        '$phases.endDate',
      taskId:              '$phases.tasks.taskId',
      taskCategory:        '$phases.tasks.category',
      taskName:            '$phases.tasks.taskName',
      taskAssignedTo:      '$phases.tasks.assignedTo',
      taskStatus:          '$phases.tasks.status',
      taskDueDate:         '$phases.tasks.dueDate',
      taskCompletedDate:   '$phases.tasks.completedDate',
      subtaskId:           '$phases.tasks.subtasks.subtaskId',
      subtaskName:         '$phases.tasks.subtasks.name',
      subtaskCompletedBy:  '$phases.tasks.subtasks.completedBy',
      checklistTotal:      '$phases.tasks.subtasks.checklist.totalItems',
      checklistCompleted:  '$phases.tasks.subtasks.checklist.completedItems',
      checklistApprovedBy: '$phases.tasks.subtasks.checklist.approvedBy',
    },
  },
];
