// V2 approach: MongoDB $unwind subscription.plan.features[], then $project flat
module.exports = [
  { $unwind: { path: '$subscription.plan.features', preserveNullAndEmptyArrays: true } },
  {
    $project: {
      _id: 0,
      serviceId:            1,
      employeeId:           1,
      employeeName:         1,
      department:           1,
      status:               1,
      assignedDate:         1,
      removedDate:          1,
      deploymentMethod:     1,
      appName:              '$application.name',
      appVendor:            '$application.vendor',
      appVersion:           '$application.version',
      appCategory:          '$application.category',
      supportTier:          '$application.provider.supportTier',
      accountManager:       '$application.provider.accountManager',
      contractRenewal:      '$application.provider.contractRenewalDate',
      slaHours:             '$application.provider.support.slaResponseHours',
      escalationPolicy:     '$application.provider.support.escalation.escalationPolicy',
      licenseId:            '$subscription.licenseId',
      assignedSeat:         '$subscription.assignedSeat',
      seatType:             '$subscription.seatType',
      costPerSeatUsd:       '$subscription.costPerSeatUsd',
      billingCycle:         '$subscription.billingCycle',
      expiryDate:           '$subscription.expiryDate',
      planName:             '$subscription.plan.planName',
      featureName:          '$subscription.plan.features.featureName',
      featureEnabled:       '$subscription.plan.features.enabled',
      featureEnabledDate:   '$subscription.plan.features.enabledDate',
      limitMaxStorage:      '$subscription.plan.features.limits.maxStorage',
      limitMaxUsers:        '$subscription.plan.features.limits.maxUsers',
      limitApiCallsPerDay:  '$subscription.plan.features.limits.apiCallsPerDay',
      lastActiveDate:       '$usage.lastActiveDate',
      isActive:             '$usage.isActive',
      totalLogins:          '$usage.totalLogins',
      avgSessionMinutes:    '$usage.avgSessionMinutes',
      logins30d:            '$usage.metrics.loginCount30d',
      dataTransfer30dMb:    '$usage.metrics.dataTransferMb30d',
      errorRate:            '$usage.metrics.errorRate',
      auditStatus:          '$compliance.auditStatus',
      lastAuditDate:        '$compliance.lastAuditDate',
      dataClassification:   '$compliance.dataClassification',
    },
  },
];
